name: Deploy API to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug EC2_HOST value
      run: echo "Host is ${{ secrets.EC2_HOST }}"

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

    - name: Deploy API to EC2
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/ubuntu/health-monitor/api
          git fetch origin
          git reset --hard origin/main
          git pull origin main
          npm install
          npm run build
          pm2 restart nestjs-api
        EOF
